### ISSUE TITLE
Paladin's Seal of Vengeance

### ISSUE THREAD

**Issue by GMFluxxed** [Unlimited-WoW/BugTracker#50]
**Description:**

Paladin's Seal of Vengeance  gives Seal of Righteousness instead.

**Current behaviour:**

Gives Seal of Righteousness.

**Expected behaviour:**

Give Seal of Vengeance

**Steps to reproduce the problem:**

1. Step 1 Use Seal of Vengeance  
2. Step 2 Look at buffs
3. Step 3 It has given you Seal of Righteousness

**Comment by Noxiide** [comment]
This was done intentionally for seal of vengeance/corruption was way too overpowered.
it's like hunter detterance doesn't work, it gives bubble.
rogues evasion doesn't work, it gives retalliation.
mage combustion doesn't work, it gives a 20% damage increase buff instead.

all these and more spells are done intentionally because they were either bugged/OP/useless at these high stats.
